name: 'Terraform'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: "us-west-2"
  ENVIRONMENT_STAGE: "dev"

jobs:
  deploy-terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./env/dev
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.IAM_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActionsSession

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" -backend-config="key=dev/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=terraform.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=terraform.tfvars
